[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
admin_passwd = $pbkdf2-sha512$600000$VipFqDWmNGZsjTFmbI2x1g$jTMiABbb6ubZL0/qOQEyj2vzOHwhEUNiKWL0ZUVkizi1R2IC02JzLKs1a6cmy/O2bN5NBumpIxjGz.MUDVbUUg

